---
- name: Include platform-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: Install WAF
  ansible.builtin.import_tasks: install_waf.yml

- name: Test WAF
  when: test_waf
  block:
    - name: Test webserver using attack like GET
      ansible.builtin.uri:
        url: "{{ item }}"
        status_code: 403
        validate_certs: "{{ test_waf_validate_certs }}"
      register: _result
      failed_when: _result.status != 403
      with_items: "{{ test_waf_urls }}"
