---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Test webserver using attack like GET
      ansible.builtin.uri:
        url: http://localhost/?e=/bin/bash
        status_code: 403
      register: _result
      failed_when: _result.status != 403
