---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: debian10
    image: bwinfosec/debian10-systemd
    privileged: true
    override_command: false
    networks:
      - name: molecule_test_network
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
  - name: debian11
    image: bwinfosec/debian11-systemd
    privileged: true
    override_command: false
    networks:
      - name: molecule_test_network
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
verifier:
  name: ansible
